### ISSUE TITLE
Does fine-grained classification accuracy improved?

### ISSUE THREAD

**Issue by joeysu** [tzzcl/RNN-HA#1]
Nice work!
 
I have a question about this paper.

Does the RNN-HA architecture help to improve classification (e.g. vehicle make/model/type/color ...) accuracy?

**Comment by tzzcl** [comment]
Hi, Thank you for your interest in our work!

Actually, we don't test the RNN-HA architecture on the classification tasks, and you can directly try it!

 However, re-identification is much harder than classification, our performance gap on RNN-HA shows that RNN-HA may also help the classification tasks!

Thank you!

**Comment by joeysu** [comment]
@tzzcl 

Thanks for your quick reply, I would like to try it.

Another question is about the inference speed of RNN-HA.

I'm looking forward to your reply! Thank you!

**Comment by tzzcl** [comment]
@s5plus1 I don't understand the problem.

Do you want to ask the inference speed of RNN-HA, or some other problems?

**Comment by joeysu** [comment]
sorry, I want to ask the inference speed of RNN-HA.

在 2018年12月13日，12:13，Chen-Lin Zhang <notifications@github.com<mailto:notifications@github.com>> 写道：


@s5plus1<https://github.com/s5plus1> I don't understand the problem.

Do you want to ask the inference speed of RNN-HA, or some other problems?

**Comment by tzzcl** [comment]
RNN-HA takes about 0.3s when infers a single image with a K80 GPU on our server (but I don't measure it precisely).

**Comment by joeysu** [comment]
@tzzcl 
Thank you!

Would you provide pre-trained model? Like "checkpoint.pth.tar" in "main_GRU_fusion_attention_test.py".

**Comment by tzzcl** [comment]
@s5plus1 
Hi, I am sorry to tell you that due to dataset license issues, we can't provide pre-trained models.

But you can try to access these two datasets on your own, and train the model by yourself.

**Comment by joeysu** [comment]
@tzzcl 

That’s ok, thanks anyway!

I will try it.
